"""empty message

Revision ID: 0762e480a73d
Revises: 58227a332d7d
Create Date: 2021-11-18 16:10:49.606986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0762e480a73d'
down_revision = '58227a332d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('location', sa.String(length=50), nullable=True))
    op.drop_column('application', 'city_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('city_location', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('application', 'location')
    # ### end Alembic commands ###
