"""posts table

Revision ID: 71689604158f
Revises: 68d4a2174e66
Create Date: 2021-11-14 13:39:22.330080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71689604158f'
down_revision = '68d4a2174e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_timestamp'), 'job', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_timestamp'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
