"""empty message

Revision ID: 83ad2cb5f937
Revises: 1263db1e210d
Create Date: 2021-11-19 00:35:41.898014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ad2cb5f937'
down_revision = '1263db1e210d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_application_timestamp'), 'application', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_timestamp'), table_name='application')
    op.drop_column('application', 'timestamp')
    # ### end Alembic commands ###
