"""empty message

Revision ID: b43c107f855b
Revises: 39ed464f731b
Create Date: 2021-11-18 01:28:17.645696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43c107f855b'
down_revision = '39ed464f731b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'category')
    # ### end Alembic commands ###
