"""empty message

Revision ID: da27f1ae349c
Revises: d1d181ffd048
Create Date: 2021-11-17 13:57:22.214486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da27f1ae349c'
down_revision = 'd1d181ffd048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=50), nullable=True),
    sa.Column('city_location', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_application_timestamp'), 'application', ['timestamp'], unique=False)
    op.add_column('job', sa.Column('datecreated', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('location', sa.String(length=100), nullable=True))
    op.drop_index('ix_job_timestamp', table_name='job')
    op.create_index(op.f('ix_job_datecreated'), 'job', ['datecreated'], unique=False)
    op.drop_column('job', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_job_datecreated'), table_name='job')
    op.create_index('ix_job_timestamp', 'job', ['timestamp'], unique=False)
    op.drop_column('job', 'location')
    op.drop_column('job', 'datecreated')
    op.drop_index(op.f('ix_application_timestamp'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
